### ISSUE TITLE
Crashes on 1.16.5-1.19.2

### ISSUE THREAD

**Issue by iinterp** [RedLime/SleepBackground#17]
Attempting to launch Minecraft with sleepbackground installed on 1.16.5, 1.17.1, 1.18.1, 1.18.2 or 1.19.2 instantly crashes.

Probably all versions 1.16.5-1.19.2 do this, but these are the only versions I tested.

Tested with:
`sleepbackground-3.9-1.18.2-1.19.x.jar` - Crashes on 1.18.2 & 1.19.2, works on 1.19.4
`sleepbackground-3.9-1.16.x-1.18.1.jar` - Crashes on 1.16.5, 1.17.1 & 1.18.1, works on 1.16.1
`Fabric Loader 0.15.6`
`Java 20.0.1`
With no other mods

[Crash log](https://mclo.gs/OdEQUzg) (1.19.2)
[Crash log](https://mclo.gs/0A51gVW) (1.16.5)

**Comment by tildejustin** [comment]
unlucky that a little startIntegratedServer target has this effect, should be fixable with a requires 1 manually remapped dual target injector.

**Comment by tildejustin** [comment]
i think the 1.20 version is fine
